In [1]:
#basics
import numpy as np
import pandas as pd
pd.set_option('display.max_columns',500)
pd.set_option('display.max_rows', 300)

#files 
import pickle

#plots
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

#ignore warnings
import warnings
warnings.filterwarnings('ignore')

Previously, selected likely to be useful columns from a sqlite database of 1.88 million fires between 1992-2015.

In [ ]:
import sqlite3
conn = sqlite3.connect("/home/douglas/Downloads/FPA_FOD_20170508.sqlite")

# Feature cleaning

In [2]:
#load in sample of 10k observations, with some columns already removed
with open('useful_fires_cols.pkl', 'rb') as picklefile:
    fires = pickle.load(picklefile)
fires.shape

In [4]:
fires.head()

,FOD_ID,SOURCE_SYSTEM_TYPE,NWCG_REPORTING_AGENCY,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,STATE,COUNTY
59905,60503,FED,FS,1993,2449184.5,197,1408,1.0,Lightning,0.10,A,43.713333,-120.997222,OR,None
1634526,201707399,NONFED,ST/C&L,2012,2456252.5,326,None,9.0,Miscellaneous,2.00,B,33.315121,-96.629963,TX,Collin
1138908,1388512,NONFED,ST/C&L,1994,2449525.5,173,None,7.0,Arson,47.00,C,33.750000,-117.248889,CA,None
1289748,1760509,NONFED,ST/C&L,2009,2455012.5,181,0605,9.0,Miscellaneous,0.10,A,41.374474,-73.967677,NY,ORANGE
1193939,1447871,NONFED,ST/C&L,2010,2455404.5,208,None,9.0,Miscellaneous,1.55,B,40.770319,-73.289108,NY,SUFFOLK

### Convert dates from julian and extract month

In [5]:
fires['DISCOVERY_DATE'] = pd.to_datetime(fires['DISCOVERY_DATE'], unit='D', origin='julian') #julian dates
fires['Month'] = fires['DISCOVERY_DATE'].dt.month
fires.head(3)

,FOD_ID,SOURCE_SYSTEM_TYPE,NWCG_REPORTING_AGENCY,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,STATE,COUNTY,Month
59905,60503,FED,FS,1993,1993-07-16,197,1408,1.0,Lightning,0.1,A,43.713333,-120.997222,OR,None,7
1634526,201707399,NONFED,ST/C&L,2012,2012-11-21,326,None,9.0,Miscellaneous,2.0,B,33.315121,-96.629963,TX,Collin,11
1138908,1388512,NONFED,ST/C&L,1994,1994-06-22,173,None,7.0,Arson,47.0,C,33.750000,-117.248889,CA,None,6

In [6]:
fires['DayofWeek'] = fires['DISCOVERY_DATE'].dt.weekday
fires.head(1)

In [7]:
fires.head(1)

,FOD_ID,SOURCE_SYSTEM_TYPE,NWCG_REPORTING_AGENCY,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,STATE,COUNTY,Month,DayofWeek
59905,60503,FED,FS,1993,1993-07-16,197,1408,1.0,Lightning,0.1,A,43.713333,-120.997222,OR,None,7,4